### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hansmach1ne** [eroloo/ctf#1]
How did you connect to port 22 on knock knock challenge, when knockd is keeping it closed. You didn't mention the banner on FTP service it shows you that port 7000, 8000 and 9000 are used as knocking sequence to open SSH port.

My understanding is when you knock on those ports in exactly that sequence with: knock IP_ADDR 7000, 8000, 9000, SSH will only then open. And only then will you be able to connect with the key? Please clarify.

**Comment by eroloo** [comment]
@hansmach1ne thank you for question. It seems that I was using 
``` nmap -p T:1-10000 ``` three times which performs tcp knocking in the background  - I have checked that and that opens a ssh port 

more gentle solution would be 
nc 192.168.56.101 7000
nc 192.168.56.101 8000
nc 192.168.56.101 9000

feel free to ask me if you have any other questions

**Comment by hansmach1ne** [comment]
Thank you for clarification.
